### PR TITLE
33666 Changed handling of Error instance in logger, to prevent concat of msg and error.message

### PR DESCRIPTION
**Pull request by danwilliams**

### CODE REVIEW

**Comment by jon-shipley** [comment]
This concatenation is most likely coming from Winston.  I'd suggest upgrading Winston to the latest version and checking the config/source code to see why it is happening.

**Comment by GuyHarwood** [comment]
@jon-shipley both winston and app insights adapter for winston are current.  
@danwilliams can we have a manual workaround/hack for this please

**Comment by jon-shipley** [comment]
@GuyHarwood - to get a clear separation of the error Id and the concatenated message all that is required is a space at the end of our message.

To get a clear separation throughout we could add a space to the end of every one of our messages in the logger model.

```javascript
  log (level, msg, exception) {
    this.logger.log(level, msg + ' ', exception)
  }
```

**Comment by GuyHarwood** [comment]
@jon-shipley @danwilliams sounds like the best way to get this sorted and off the table for now 👍

**Comment by danwilliams** [comment]
As you point out, winston is already on the latest version. The cause of this is winston appending `exception.message` if the exception is an `Error` e.g.
```msg = 'ERROR: Not Found ID: 4d28d8d5-0ac5-4e92-a20f-77fd59b1b874'
exception = {
  message: 'Not Found',
  stack: 'foo-bar'
}
```
Results in Winston logging:
```ERROR: Not Found ID: 4d28d8d5-0ac5-4e92-a20f-77fd59b1b874Not Found
{
  message: 'Not Found',
  stack: 'foo-bar'
}
```

My solution is to look for the `message` property and restructure the extra data so Winston just prints it in the console:
```ERROR: Not Found ID: 4d28d8d5-0ac5-4e92-a20f-77fd59b1b874
{
  error:
    message: 'Not Found',
    stack: foo-bar'
  }
}
```

Adding a space is a quick fix, but doesn’t seem any _better_ than what I’ve done.

e.g.
Your way:
```error: ERROR: Not Found ID: 928ce1dc-a7d9-4be2-8272-d54e729666c3 Not Found {"status":404,"stack":"Error: Not Found\n    at ..."}
```
My way:
```error: ERROR: Not Found ID: ece97513-4411-4e8d-9ab8-21d6f0d85538 {"error":{"stack":"Error: Not Found\n    at ...","message":"Not Found","status":404}}
```

@GuyHarwood Can you confirm what you would like to do?

**Comment by GuyHarwood** [comment]
@danwilliams this has been tested in azure and it did not work.  So we should add the spacing in the logger model.

**Comment by GuyHarwood** [comment]
Closing as fixed on another branch

**Pull request closed without merging**
