### PR TITLE
Feature/security roll up

### PR DESCRIPTION
**Pull request by activemq**
Rollup of security prs

### CODE REVIEW

**Review by GuyHarwood — APPROVED** [review]
LGTM

**Comment by jon-shipley** [comment]
@GuyHarwood @activemq I don't understand why we are patching code under `z_archive`?

I would think either deleting the code or instructing Dependabot to ignore that path would be appropriate as it is historical, isn't it?

**Comment by GuyHarwood** [comment]
good spot @jon-shipley 

i'd prefer to just delete it, as part of this PR

**Comment by GuyHarwood** [comment]
regarding ignores - would be good to do that for the spikes folder

**Pull request merged**
