### PR TITLE
Feature/19548 spa inject env vars runtime

### PR DESCRIPTION
**Pull request by danwilliams**

### CODE REVIEW

**Comment by GuyHarwood** [comment]
impressed that you found a way around this.   although it does feel like a lot more moving parts than our current approach. 🤔

**Comment by danwilliams** [comment]
Yes, for sure! It may not be suitable. However I think it will still work with the system constraints... and the extra moving parts only have to be set up once 😄

**Comment by GuyHarwood** [comment]
yes, good point.  when ive got the HLD out of the way we should organise a time to go through it, see it in action etc

**Comment by danwilliams** [comment]
Awesome! 😄

**Pull request merged**
