### PR TITLE
Add anonymization IP support for admin and pupil apps

### PR DESCRIPTION
**Pull request by GeorgeChatzigiannis**
Actions:

- Updated angulartics to 5.3.0 as per https://github.com/angulartics/angulartics2/issues/250 (pupil)
- Passed the anonymize_ip attribute as true within the gtag config (admin)

### CODE REVIEW

**Comment by GuyHarwood** [comment]
@GeorgeChatzigiannis when you say `verify both apps are using the anonymization IP feature` do you mean to actually run and test it?

**Comment by GeorgeChatzigiannis** [comment]
@GuyHarwood yes I now have two tracking codes that can be used to test these changes.
I will report back as soon as I test these changes.

**Comment by GeorgeChatzigiannis** [comment]
For both admin and pupil app request URL contains the parameter `aip=1` which confirms the IP anonymization.

**Comment by GuyHarwood** [comment]
@GeorgeChatzigiannis can you demo this to a BA please and expedite sign-off?

**Comment by GeorgeChatzigiannis** [comment]
@GuyHarwood shouldn't it go through QA testing first?

**Comment by GeorgeChatzigiannis** [comment]
@sinhaamit1980 will be testing this and will go through sign-off

**Pull request merged**
