### PR TITLE
feature/automation-test-for-hpa

### PR DESCRIPTION
**Pull request by sinhaamit1980**

### CODE REVIEW

**Comment by GuyHarwood** [comment]
@sinhaamit1980 this PR has been inactive for some time now - is it ready to merge?  if not, we should close it until you are ready to come back to it.

**Comment by sinhaamit1980** [comment]
> @sinhaamit1980 this PR has been inactive for some time now - is it ready to merge? if not, we should close it until you are ready to come back to it.

I just finished the automation test for admin app for New HPA…but I need to run one complete test suite after all bugs that I have raised for  HPA will be fixed to make sure its passing and not flaky
Also I will have to discuss with Mo and pick up the pupil spa automation test for HPA which Mo has also started on this PR only

**Comment by GuyHarwood** [comment]
@sinhaamit1980 closing this until you come back to it.  have removed CI tag too

**Comment by jon-shipley** [comment]
@sinhaamit1980 @activemq 

There are a bunch of screen shots that are checked in on this branch - they need to be removed please before merging.

**Comment by jon-shipley** [comment]
@sinhaamit1980 @activemq - I was also expecting to see the prepareCheckMessaging set to true in this PR.

**Comment by GuyHarwood** [comment]
@jon-shipley this is what i was explaining yesterday - i created a new travis-hpa feature toggle profile, and it needs enabling in this branch by setting `ENVIRONMENT_NAME` to match.

I will go through this with Amit next week.

**Comment by GuyHarwood** [comment]
@jon-shipley this green build is effectively a false positive.  same for the SPA

**Comment by sinhaamit1980** [comment]
> @sinhaamit1980 @activemq
> 
> There are a bunch of screen shots that are checked in on this branch - they need to be removed please before merging.

@jon-shipley - removed all the screenshots

**Pull request merged**
