### PR TITLE
Add pupil-spa cucumber tests to travis build

### PR DESCRIPTION
**Pull request by jon-shipley**

### CODE REVIEW

**Comment by jon-shipley** [comment]
@activemq - tests are currently broken - can you have a look please?

**Comment by jon-shipley** [comment]
@activemq - looks like the build are now green 👍 Many thanks.   Can you approve the PR if you are happy?

**Comment by activemq** [comment]
@jon-shipley @GuyHarwood - Only admin and pupil-spa tests are running, don't we want to be running the pupil tests also?

**Comment by jon-shipley** [comment]
@activemq @GuyHarwood 

I don't think so as they will be deleted soon.  In any case - outside of this ticket?

**Comment by activemq** [comment]
@jon-shipley ok no worries

**Comment by jon-shipley** [comment]
@activemq - looks like your last merge broke the tests here.  Can you support?

**Pull request merged**
