### PR TITLE
Feature/13906 docker compose

### PR DESCRIPTION
**Pull request by GuyHarwood**
Local dev environment setup via docker compose.

Run `docker-compose up` to run.

Containers for existing pupil & admin apps
Container for MongoDB
Container for RabbitMQ
Container for new pupil SPA

### CODE REVIEW

**Comment by jon-shipley** [comment]
@guy, for a local dev setup developers would almost certainly run the application locally, e.g. `npm start` and use docker services for everything else.

Additionally, it didn't work for me:

```
jon@spaceship:projects/MTC/ > docker-compose up
Creating network "mtc_default" with the default driver
Building pupil-spa
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 118, in perform_command
  File "compose/cli/main.py", line 926, in up
  File "compose/project.py", line 401, in up
  File "compose/service.py", line 311, in ensure_image_exists
  File "compose/service.py", line 888, in build
  File "site-packages/docker/api/build.py", line 207, in build
  File "site-packages/docker/api/build.py", line 254, in _set_auth_headers
  File "site-packages/docker/auth.py", line 85, in resolve_authconfig
  File "site-packages/docker/auth.py", line 129, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-osxkeychain exited with "One or more parameters passed to a function were not valid.".',)
Failed to execute script docker-compose
```

```
jon@spaceship:projects/MTC/ > python --version
Python 3.6.1
```

**Comment by GuyHarwood** [comment]
@jon-shipley `npm start` is called within each container as part of the `docker-compose up`.  The purpose of this is to give you a one-liner to stand up all necessary services to develop locally.

With regard to the dev process, we can setup volumes for the app containers and map these locally, meaning you don't need to spin everything up each time you make changes.  Can you think of any reason why we would not want to do this?

**Comment by jon-shipley** [comment]
@GuyHarwood - after a reboot `docker-compose up` works fine!  I'm happy to give the mapped docker-compose version a try but I suspect it's more complexity than is needed.

I can see value in it for testing though.

**Comment by GuyHarwood** [comment]
@jon-shipley OK.  we should discuss as a group the +/- for development.  Although worth pointing out that nobody should dictate how you setup your local dev env!  Do what suits you 💯 

Can you please approve if you have no other concerns.

**Pull request merged**
