### PR TITLE
[admin] chore: upgrade dependencies

### PR DESCRIPTION
**Pull request by jon-shipley**

### CODE REVIEW

**Comment by GuyHarwood** [comment]
@jon-shipley PR build failing due to database connectivity issues.  Have re-started

**Comment by GuyHarwood** [comment]
@jon-shipley this is now passing on PR validation, but VSO/github has not updated the PR

**Comment by jon-shipley** [comment]
> @jon-shipley this is now passing on PR validation, but VSO/github has not updated the PR

This line appears to be odd: `[command]/home/mtcbuild01/.nvm/versions/node/v9.11.2/bin/npm install`

As
1. It should be running `yarn install`
2. The node version is wrong, should be 10.16.3 according to `.nvmrc`

**Comment by GuyHarwood** [comment]
it's been like this since it was created.  as per discussion - now uses nvm and yarn with frozen lockfile

**Comment by GuyHarwood** [comment]
now building and passing

**Pull request merged**
